document.write('<details>');
document.write('<summary>DDB ⇲</summary>');
  document.write('<details>');
  document.write('<summary><b>film</b></summary>');
    document.write('<div><a href=/film/petal.html>untitled (petal) (2025)</a></div>');
    document.write('<div><a href=/film/landscape256.html>Landscape #256 (2025)</a></div>');
    document.write('<div><a href=/film/archive.html>untitled (archive) (2024)</a></div>');
    document.write('<div><a href=/film/moon.html>untitled (moon) (2020)</a></div>');
    document.write('<div><a href=/film/inyourarms.html>In Your Arms (2020)</a></div>');
    document.write('<div><a href=/film/uc1.html>Ultimate Crush (2019)</a></div>');
    document.write('<div><a href=/film/camera_roll.html>untitled (camera roll) (2017)</a></div>');
    document.write('<div><a href=/film/summer.html>Summer (2014) (2016)</a></div>');
    document.write('<div><a href=/film/forlife.html>For Life (2015)</a></div>');
    document.write('<div><a href=/film/amv.html>「 A M V 」 (2014-2015)</a></div>');
    document.write('<div><a href=/film/hopeless.html>In a Hopeless Place (2013)</a></div>');
    document.write('<div><a href=/film/gf00.html>untitled (GF-00) (2013)</a></div>');
  document.write('</details>');
  document.write('<details>');
  document.write('<summary><b>audio</b></summary>');
      document.write('<details>');
      document.write('<summary>sad_rave</summary>');
        document.write('<div><a href=/audio/sr/clock1.html>clock movies 1 (2024)</a></div>');
        document.write('<div><a href=/audio/sr/10.html>10 (2023)</a></div>');
        document.write('<div><a href=/audio/sr/airflow.html>air flow (2021)</a></div>');
        document.write('<div><a href=/audio/sr/2403.html>2403 (2021)</a></div>');
        document.write('<div><a href=/audio/sr/CDR.html>CDR (2021)</a></div>');
        document.write('<div><a href=/audio/sr/longlive.html>longlive (2020)</a></div>');
        document.write('<div><a href=/audio/sr/dcrvx1000e.html>DCR-VX1000E (2020)</a></div>');
        document.write('<div><a href=/audio/sr/xiv.html>xiv (2018)<a></div>');
        document.write('<div><a href=/audio/sr/2014.html>2014 (2017)</a></div>');
        document.write('<div><a href=/audio/sr/addred.html>Add Red (2017)</a></div>');
        document.write('<div><a href=/audio/sr/safesound.html>safe/sound (2014)</a></div>');
        document.write('</details>');
      document.write('<details>');
      document.write('<summary>crescent arc</summary>');
        document.write('<div><a href=/audio/ca/07090310013010020123052009200522.html>07090310013010020123052009200522 (2024)</a></div>');
        document.write('<div><a href=/audio/ca/plushie.html>plushie (2022)</a></div>');
        document.write('<div><a href=/audio/ca/edits21.html>edits 2021 (2021)</a></div>');
        document.write('<div><a href=/audio/ca/spincycle.html>spin cycle (2021)</a></div>');
        document.write('<div><a href=/audio/ca/ids.html>Ikkitousen Deathmatch Survivor (2021)</a></div>');
        document.write('<div><a href=/audio/ca/bbke.html>Blood baby / kind eyes (2021)</a></div>');
        document.write('</details>');
      document.write('<details>');
      document.write('<summary>outclub</summary>');
        document.write('<div><a href=/audio/oc/save001.html>save001 (2024)</a></div>');
        document.write('<div><a href=/audio/oc/take10.html>take10 (2024)</a></div>');
        document.write('<div><a href=/audio/oc/ditto.html>Ditto (outclub『side B』12") (2023)</a></div>');
        document.write('<div><a href=/audio/oc/darksnow.html>dark snow (2022)</a></div>');
        document.write('<div><a href=/audio/oc/gacha.html>East-West Gacha Master (2021)</a></div>');
        document.write('</details>');
      document.write('</details>');
      document.write('<details>');
      document.write('<summary><b>other</b></summary>');
        document.write('<details>');
        document.write('<summary>「 PV」(2021-2023)</summary>');
          document.write('<div><a href=/other/pv/reunion.html>Cotton Mouth - Reunion (2023)</a></div>');
          document.write('<div><a href=/other/pv/dfa.html>Symrun - DFA (2022)</a></div>');
          document.write('<div><a href=/other/pv/bingo.html>Team Rockit - Bingo (2021)</a></div>');
          document.write('</details>');
        document.write('<div><a href=/other/9000000000.html>9,000,000,000 Names of God (2019)</a></div>');
        document.write('<div><a href=/other/spiritlevels.html>Spirit Levels (2017)</a></div>');
        document.write('</details>');
      document.write('<details>');
      document.write('<summary><b>info</b></summary>');
        document.write('<div><a href=/info/bio.html>bio</a></div>');
        document.write('<div><a href=/info/contact.html>contact</a></div>');
        document.write('</details>');
document.write('</details>');